### ISSUE TITLE
Query string causes URL targeting to fail.

### ISSUE THREAD

**Issue by jaredatch** [kasparsd/widget-context-wporg#14]
I have a site with this page:
acme-corp.com/campaigns/

This page contains various links, which filter the content of the page in this format:
acme-corp.com/campaigns/?cc=automotive

Targeting by URL seems to work correctly for the first URL (this is a normal WordPress page), however when any query string is in the URL the widget will not show.

So acme-corm.com/campaigns/?foobar will not show the widget either.

I am using wildcards, so I'm not sure why this isn't working. I've tried all of the following:

```
campaigns/
campaigns/*
campaigns/?cc=*
```

This has to be a bug I'm assuming. Any insight would be appreciated.

**Comment by reneneee** [comment]
This bug also makes URL targeting useless on mutlilingual site using WPML, as language by default is chosen by GET parameter, e.g. "http://example.com/page/?lang=es"

**Comment by kontrollanten** [comment]
I'm having a problem with this too. Any news about it?

**Comment by jkeasley** [comment]
Is this issue resolved in version 1.1.0, as I am still seeing this behaviour when handling urls with ?utm query strings

**Comment by kasparsd** [comment]
@jkeasley I just confirmed that it isn't working also on [this demo page](https://demo.preseto.com/widget-context/hello-world?utm_source=example) where there should be a Meta widget in the footer of the sidebar.

Re-opening.

**Comment by kasparsd** [comment]
@jkeasley Actually, the settings were missing the wildcard entry to capture all query variables. I added `widget-context/hello-world?*` to the list of URLs and now it works as expected.

Here is the full contents of the Target by URL field:

```
widget-context/hello-world
widget-context/hello-world?*
```
