### ISSUE TITLE
Re: Show or hide widgets on specific pages

### ISSUE THREAD

**Issue by thinkhuman** [kasparsd/widget-context-wporg#24]
Am I missing this feature? The plugin--which is great--says it can show/hide widgets in specific pages. This doesn't seem to be true--I can't specify which if my site's pages to display widgets on.

**Comment by kasparsd** [comment]
@thinkhuman Yes, you can use the "Target by URL" feature to specify the relative URLs of the pages you want to target. You can also use a wildcard `*` to select all child pages, etc.

**Comment by kettultim** [comment]
@kasparsd sorry to bring up an old thread but I have never been able to reliably get Target by URL to work. Every other setting works but that one doesn't. Using 1.0.4.

Settings:

**Target by URL**
page/specific-subpage
page/specific-subpage/*

**Comment by thinkhuman** [comment]
@kettultim Same. I've never got it to reliably work.

**Comment by kasparsd** [comment]
@kettultim @thinkhuman What is the URL you're targeting? What is the URL of the site / WP install? Feel free to replace the domain with example.com.

**Comment by kettultim** [comment]
@kasparsd apologies for the late reply. This is what we're using:

domain: https://example.com

**Target by URL:**
```
subpage
subpage/*
```

Tried this as well to no avail:
```
https://example.com/subpage
https://example.com/subpage/*
```

As well as just the root domain (no 'https://')

Haven't had the time to look into the plugin code - just thought you should know.

**Comment by kasparsd** [comment]
@kettultim Both should work. For example, I'm using the following rules:

![meta-widget-post-selector](https://user-images.githubusercontent.com/169055/49732449-72b43f80-fc87-11e8-8523-0e790e487ff2.png)

to show the Hello World Meta widget only on [this post](https://demo.preseto.com/widget-context/hello-world).

Which version of the plugin are you running? Could send the actual URL to `support@preseto.com`?

**Comment by kettultim** [comment]
@kasparsd using 1.0.4

I can confirm it works except in this particular instance... perhaps due to the path starting with a number?

For example, it works on `news` but not on `2018news`

**Comment by kasparsd** [comment]
@kettultim Could you please try the latest version 1.1.0 of the plugin? There have been [a lot of changes to the plugin since version 1.0.4](https://github.com/kasparsd/widget-context-wporg/compare/1.0.4...master).

**Comment by kettultim** [comment]
Geez I'm so sorry.. I thought we were already on the latest. Hadn't checked Multisite. Works as intended on 1.1.0. One of those duh moments :(
