### ISSUE TITLE
Incorrect paths for admin CSS and JS

### ISSUE THREAD

**Issue by tedgeving** [kasparsd/widget-context-wporg#31]
The following errors are occurring in the latest release of the plugin:

`GET http://j3.test/wp-content/plugins/widget-context/class/css/admin.css?ver=1.0.4 net::ERR_ABORTED`

`GET http://j3.test/wp-content/plugins/widget-context/class/js/widget-context.js?ver=1.0.4 net::ERR_ABORTED`

The plugin is looking for `admin.css `and `widget-context.js` in the class folder instead of one directory up.

Created a pull request:
https://github.com/kasparsd/widget-context-wporg/pull/32

**Comment by kasparsd** [comment]
Fixed in #32
