### ISSUE TITLE
Feature request: filter widgets in the admin widgets page

### ISSUE THREAD

**Issue by johnh10** [kasparsd/widget-context-wporg#57]
So I have many different widgets to show for many different pages, but the widgets page in the WordPress Admin area shows all of them together and I have to figure out which to work on for whatever page I'm updating.

Is it possible to add a filter to the WordPress admin widgets page to only display widgets that pass the filter? For instance I could tell the filter to only show widgets that are set to display on the front page, or on page X, etc.  That would help tremendously in setting up/updating the widgets. This is only for the admin area and not the front end.

**Comment by kasparsd** [comment]
That's a great idea!

The WordPress Customizer actually shows the widgets greyed out if they're hidden in the current preview:

![widgets-hidden](https://user-images.githubusercontent.com/169055/80079120-86003c00-8558-11ea-8cd4-ddc022915e09.png)

Does that help?

**Comment by johnh10** [comment]
I think that will work. I'll recommend people use the customizer over the widget page then.
